config/routes.rb
# frozen_string_literal: true

Rails.application.routes.default_url_options[:host] = ENV.fetch('BASE_URL', nil)

Rails.application.routes.draw do
  root to: 'home#index'

  scope module: :web do
    resources :users
    resource :session, only: :destroy

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :repositories do
      resources :checks, only: %i[show create]
    end
  end

  namespace :api do
    post 'checks', to: 'checks#create', as: :checks
  end
end

app/views/layouts/shared/_flash.html.slim
 - if flash.any?
  .container.my-2
    - flash.each do |_type, msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_nav.html.slim
header.p-3.bg-dark.text-white
  .container
    .nav.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        li.nav-item.me-2
          = link_to t('home'), root_path, class: 'nav-link text-white'
          - if signed_in?
            li
              = link_to t('repositories'), repositories_path, class: 'nav-link text-white'
      ul.nav.col-12.col-lg-auto.mb-2.mb-md-0
        - if signed_in?
          li.nav-item
            = link_to '#', class: 'nav-link text-secondary' do
              = current_user.email
          li.nav-item.me-2
            = link_to session_path, class: 'nav-link text-white', method: :delete do
              = t('user.log_out')
        - else
          li.nav-item.me-2
            = link_to auth_request_path('github'), method: :post, class: 'nav-link text-white' do
              span.bi.bi-github.me-2
                = image_tag asset_pack_path('media/images/github.svg')
              = t('log_in')