config/routes.rb
# frozen_string_literal: true

Rails.application.routes.default_url_options[:host] = ENV.fetch('BASE_URL', nil)

Rails.application.routes.draw do
  root to: 'home#index'

  scope module: :web do
    resources :users
    resource :session, only: :destroy

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth

    resources :repositories do
      resources :checks, only: %i[show create]
    end
  end

  namespace :api do
    post 'checks', to: 'checks#create', as: :checks
  end
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  belongs_to :user
  has_many :checks, class_name: 'Repository::Check', dependent: :destroy

  validates :github_id, presence: true, uniqueness: true

  extend Enumerize
  enumerize :language, in: %i[javascript ruby]
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  belongs_to :repository

  include AASM

  aasm do
    state :created, initial: true
    state :checking
    state :finished
    state :failed

    event :to_check do
      transitions from: :created, to: :checking
    end

    event :to_finish do
      transitions from: :checking, to: :finished
    end

    event :to_fail do
      transitions to: :failed
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = Repository.where(user_id: current_user.id)
  end

  def new
    @repository = current_user&.repositories&.new
    repos_names
  end

  def create
    @repository = current_user.repositories.build(permitted_params)

    if @repository.save
      url_webhook = url_for(controller: 'api/checks', action: 'create')
      repository_loader.repo_job(@repository, current_user, url_webhook)

      redirect_to repositories_path, notice: t('repo_created')
    else
      repos_names
      flash[:notice] = @repository.errors.full_messages.to_sentence
      render :new, locals: { repos: @repos }, status: :found
      flash.clear
    end
  end

  def show
    @repository = Repository.find params[:id]
    @checks = @repository.checks.order(created_at: :desc)
  end

  private

  def repos_names
    language_list = Repository.language.values
    client = repository_loader.octokit_client(current_user.token)
    @repos = Rails.cache.fetch('repos_name', expires_in: 12.hours) do
      repository_loader.get_repos(client).each_with_object([]) do |item, array|
        array << [item[:full_name], item[:id]] if language_list.include?(item[:language]&.downcase)
      end
    end
  rescue Octokit::Unauthorized
    redirect_to root_path, notice: t('repo_token')
  end

  def permitted_params
    params.require(:repository).permit(:github_id)
  end

  def repository_loader
    ApplicationContainer[:repository_loader]
  end
end

app/views/web/repositories/_form.html.slim
= simple_form_for(@repository) do |f|
  = f.select :github_id, @repos, { include_blank: true }, { class: 'form-control' }
  = f.button :submit, class: 'btn btn-success mt-4 btn-block'

app/views/web/repositories/index.html.slim
- content_for :title do
  = t('repositories')

.mb-3 = link_to t('new'), new_repository_path, class: 'btn btn-primary'

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } = t('name')
      th{ scope: :col } = t('language')
      th{ scope: :col } = t('last_check_passed')
      th

  tbody
    - @repositories.each do |repository|
      tr
        td = link_to repository_path(repository) do
          = repository.name
        td = repository.language
        td = repository.checks.last&.passed
        td

app/views/web/repositories/new.html.slim
- content_for :title do
  = t('new_repository')

== render 'form'

hr

= link_to t('back'), :back, class: 'btn btn-outline-primary'

app/views/web/repositories/show.html.slim
h1 = @repository.full_name

.mb-3.mt-3
  .btn-group
    - if @repository.checks.last&.checking? || @repository.checks.last&.created?
      - flash[:notice] = t('repo_show')
      .spinner-border.me-2 role="status"
        span.visually-hidden t('load')
      = link_to t('update_status'), repository_path(@repository.id), class: 'btn btn-outline-success'
    - else
      - flash.clear
      = link_to t('check'), repository_checks_path(@repository.id), method: :post, class: 'btn btn-outline-primary'

- content_for :title do
  = @repository.full_name

p
  strong.me-2 Name
  = @repository.name
p
  strong.me-2 Language
  = @repository.language
p
  strong.me-2 Created At
  - if @repository.repo_created_at
    = l(@repository.repo_created_at, format: :long)
p
  strong.me-2 Updated_at
  - if @repository.repo_updated_at
    = l(@repository.repo_updated_at, format: :long)

hr

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th = '#'
      th{ scope: :col } = t('state')
      th{ scope: :col } = t('reference')
      th{ scope: :col } = t('check_passed')
      th{ scope: :col } = t('check_created')
      th

  tbody
    - @checks.each do |check|
      tr
        - if check.finished?
          div
            td = link_to check.id, repository_check_path(@repository, check)
        - else
          div
            td = check.id
        td = check.aasm_state
        td = link_to check.reference&.split('/')&.last&.to_s&.slice(0, 7), check.reference
        td = check.passed
        td = check.created_at
        td